# Generated by Django 4.0.3 on 2022-05-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('placa', models.CharField(max_length=40, verbose_name='Placa')),
                ('year', models.CharField(max_length=10, verbose_name='Año')),
                ('model', models.CharField(max_length=10, verbose_name='Modelo')),
                ('tecno', models.DateField(max_length=10, verbose_name='tecnomecanica')),
                ('soat', models.DateField(max_length=10, verbose_name='Soat')),
                ('oil_change', models.DateField(max_length=10, verbose_name='Cambio de aceite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('salary', models.FloatField(max_length=100, verbose_name='Salario')),
                ('pay_day', models.DateField(verbose_name='Dia de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='Id')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('start_date', models.DateField(max_length=10, verbose_name='Fecha inicial')),
                ('end_date', models.DateField(max_length=10, verbose_name='Fecha final')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('amount', models.FloatField(max_length=100, verbose_name='Valor')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
        ),
    ]
