# Generated by Django 4.0.3 on 2022-05-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('salary', models.FloatField(max_length=100, verbose_name='Salario')),
                ('pay_day', models.IntegerField(verbose_name='Dia de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='Id')),
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
