# Generated by Django 4.0.3 on 2022-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_info_alter_expenses_category_delete_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='pay_day',
            field=models.DateField(verbose_name='Dia de pago'),
        ),
    ]
